# One Dark
[colors]
draw_bold_text_with_bright_colors = true 

[colors.primary]
background = "#282C34"
foreground = "#dcdfe4"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#dcdfe4"
yellow = "#d19a66"

[colors.bright]
black = "#5d677a"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#dcdfe4"
yellow = "#d19a66"

[colors.dim]
black = '#1e2127'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#828791'
