#!/usr/bin/env bash
#
CPU_TEMP_PATH="/sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input"
cpu_temp=$(cat $CPU_TEMP_PATH 2>/dev/null || echo 0)
cpu_temp_c=$((cpu_temp / 1000))

echo "${cpu_temp_c:-null}°C"
