[defaults]
format = "{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
time_format = "%M:%S"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
time_format = "%M:%S"
command = "notify-send 'Rest Done!'"

[[sessions]]
id = "work2"
name = "Work"
duration = "25m"
time_format = "%M:%S"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest2"
name = "Rest"
duration = "5m"
time_format = "%M:%S"
command = "notify-send 'Rest Done!'"

[[sessions]]
id = "work3"
name = "Work"
duration = "25m"
time_format = "%M:%S"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest3"
name = "Rest"
duration = "5m"
time_format = "%M:%S"
command = "notify-send 'Rest Done!'"

[[sessions]]
id = "work4"
name = "Work"
duration = "25m"
time_format = "%M:%S"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest4"
name = "Rest"
duration = "5m"
time_format = "%M:%S"
command = "notify-send 'Rest Done!'"
